apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "impostor.serviceAccountName" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: agones-allocator
subjects:
  - kind: ServiceAccount
    name: {{ include "impostor.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}